name: 208450

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecuta el workflow todos los días a las 12 PM CST
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest tareas/208450/test_funciones.py # Apunta a los tests de la tarea 208450
