name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456

    runs-on: ubuntu-latest

    steps:
      - name: "Display Message"
        run: echo "Hola mundo"

      - name: "Mostrando variable de entorno"
        run: |
          echo "Esto es el valor de platform: ${{ env.platform }}"

      - name: "Mostrar todas las variables de entorno"
        run: printenv
