name: Build Sphinx Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'documentacion/src/Calculadora.py'  # Se activa solo si hay cambios en este archivo

  pull_request:
    branches:
      - main
    paths:
      - 'documentacion/src/Calculadora.py'  # Se activa solo si hay cambios en este archivo

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Generar la documentación con Sphinx
      - name: Build Sphinx Documentation
        run: |
          cd documentacion/docs
          sphinx-build -b html . _build/html

      # 5. Configurar nombre y correo para el commit
      - name: Set git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 6. Actualizar el archivo HTML si hay cambios
      - name: Commit and push changes
        if: github.repository == 'fddo24ga/GithubActions_fddo24_test' # Ejecuta esto solo en el repositorio original
        run: |
          cd documentacion/docs/_build/html
          git add .
          git commit -m "Actualizar documentación"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utiliza el token de GitHub para realizar el push
